import Navbar from "@/components/layout/Navbar";
import "./globals.css";

import { Nunito_Sans } from "next/font/google";

// Fonts
const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-nunito",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${nunito.className} h-full scroll-smooth antialiased`}
    >
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
